# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    name: sintemal/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: sintemal/zola-deploy-action
      uses: sintemal/zola-deploy-action@master
      env:
        PAGES_BRANCH: gh-pages
        BUILD_DIR: .
        TARGET_REPOSITORY: sintemal/sintemal.github.io 
        TOKEN: ${{ secrets.TOKEN }}
